### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by ghost** [andrewheekin/csv2flare.json#1]
Hello, 

First of all thanks for sharing your code, but there is an error line 29

flare = {"name":"flare", "children": []}
must be 
d = {"name":"flare", "children": []}

Except of that it works fine.

One question, I cannot manage to add a new layer of nesting, could please share a exameple with a third layer of nesting ?

Thanks.
Emmanuel.

**Comment by andrewheekin** [comment]
updated
